// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_9eCSg-UBECMM9ZtqGJZQADS99DVC2iA',
    appId: '1:243855296988:web:9c95c85b98355259a86719',
    messagingSenderId: '243855296988',
    projectId: 'citysignseeing',
    authDomain: 'citysignseeing.firebaseapp.com',
    storageBucket: 'citysignseeing.appspot.com',
    measurementId: 'G-6JXCGDKRY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-ZrE9pqkLjUJyOndl6jcJ5Agsd6EK7Y',
    appId: '1:243855296988:android:c3e0c420f4242514a86719',
    messagingSenderId: '243855296988',
    projectId: 'citysignseeing',
    storageBucket: 'citysignseeing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36wvwaOYS-M2vIt0Z644rvc91d3R1DKU',
    appId: '1:243855296988:ios:ee6e667071dccdc1a86719',
    messagingSenderId: '243855296988',
    projectId: 'citysignseeing',
    storageBucket: 'citysignseeing.appspot.com',
    androidClientId: '243855296988-70sv9koram4t1pu36u91qor74khp1709.apps.googleusercontent.com',
    iosClientId: '243855296988-vpmp2d6b9eos4updob3m7pp4g2r9r7pd.apps.googleusercontent.com',
    iosBundleId: 'com.citysightseeingphila.citySightseeingapp',
  );

}